services:

  # ------------------------
  # La base de données
  # ------------------------
  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
       - "3306:3306"
    networks:
      - web
  # ------------------------
  # API
  # ------------------------
  lbfapi: 
    container_name: lbfapi
    image: ghcr.io/${REGISTRY_USER_API}/lbfapi:${API_VERSION}
    restart: unless-stopped
    env_file: .env
    ports: 
      - "8081:8081"
    environment: 
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${BDD_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${BDD_PASSWORD}
    networks: 
      - web

  # ------------------------
  # SiteWeb et Dashboard
  # ------------------------
  siteweb:
    container_name: siteweb
    image: ghcr.io/${REGISTRY_USER}/siteweb:${SITEWEB_VERSION}
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  db_data:
    driver: local


