services:

  # ------------------------
  # La base de données
  # ------------------------
  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
       - "3306:3306"
    networks:
      - web

  # Il faudra l'api

  # ------------------------
  # SiteWeb et Dashboard
  # ------------------------
  siteweb:
    container_name: siteweb
    image: ghcr.io/${REGISTRY_USER}/siteweb:${SITEWEB_VERSION}
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  db_data:
    driver: local


