services:

  # ------------------------
  # SiteWeb et Dashboard
  # ------------------------
  siteweb:
    container_name: siteweb
    image: ghcr.io/${REGISTRY_USER}/siteweb:${SITEWEB_VERSION}
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
    driver: bridge


